name: Automerge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - id: dependabot-metedata
        uses: dependabot/fetch-metadata@v2

      - name: automerge non-production dependencies
        if: steps.dependabot-metedata.outputs.dependency-type != 'direct:production'
        uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target-development: patch
          target-indirect: minor
