name: Automerge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - id: dependabot-metedata
        uses: dependabot/fetch-metadata@v2

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: automerge non-production dependencies
        if: steps.dependabot-metedata.outputs.dependency-type != 'direct:production'
        uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target-development: patch
          target-indirect: minor
          github-token: ${{ steps.app-token.outputs.token }}
